apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-demo-app-config
  namespace: sre-demo
  labels:
    app.kubernetes.io/name: sre-demo-app
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8s-sre-incident-automation-platform
data:
  APP_NAME: sre-demo-app
  APP_VERSION: "0.1.0"
  APP_ENV: "dev"
  COMMIT_SHA: "local"
  READINESS_FAIL: "false"
  FAIL_STARTUP: "false"
