apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo-app
  namespace: sre-demo
  labels:
    app.kubernetes.io/name: sre-demo-app
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8s-sre-incident-automation-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sre-demo-app
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sre-demo-app
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: k8s-sre-incident-automation-platform
    spec:
      containers:
        - name: sre-demo-app
          image: sre-demo-app:local
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: sre-demo-app-config

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
